version: '3.7'
services:
    nodejs-api:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        container_name: nodejs-api
        links:
            - mongo-db
    mongo-db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: mongo-db
    mongo_seed:
        build:
            context: ./
            dockerfile: mongo_seed
        container_name: mongo_seed
        links:
            - mongo-db